/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import vista.frmProveedores;
import controlador.ProveedorControladorEliminar;
import modelo.dao.ProveedorDAO;
import modelo.vo.ProveedorVO;


/**
 *
 * @author ronal
 */
public class frmProveedoresEliminar extends javax.swing.JFrame {
    /*
    private ProveedorDAO dao;
    private ProveedorVO vo;
    private frmProveedoresEliminar vista;
    ProveedorControladorEliminar ContEli = new ProveedorControladorEliminar(vo, dao, vista);
    */
    public frmProveedoresEliminar() {
        initComponents();
        //cerrarFrame();
    }

    
    
    // ---- MÉTODOS PARA VACIAR Y LLENAR LOS CAMPOS DE TEXTO ----
    //Método para txtCodigoProveedor
    public void codigoPresionado() {
        if (txtCodigoProveedor.getText().equals("Código")) { //Si el campo tiene "Código"...
            txtCodigoProveedor.setText(""); //Quita el texto
            txtCodigoProveedor.setForeground(new Color(0x100F0F)); //Cambia de color la letra
        }

        if (txtProveedor.getText().isEmpty()) { //Si al dar clic en txtCodigo, txtProveedor está vacío...
            txtProveedor.setText("Nombre"); //Llena el campo con "Nombre"
            txtProveedor.setForeground(new Color(0x666666)); //Cambia el color del texto
        }
    }

    //Método para txtProveedor
    public void proveedorPresionado() {
        if (txtProveedor.getText().equals("Nombre")) {
            txtProveedor.setText("");
            txtProveedor.setForeground(new Color(0x100F0F));
        }

        if (txtCodigoProveedor.getText().isEmpty()) {
            txtCodigoProveedor.setText("Código");
            txtCodigoProveedor.setForeground(new Color(0x666666));
        }
    }
    
    //Método para cerrar Frame
    public void cerrarFrameEliminar() {
        dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        txtProveedor = new javax.swing.JTextField();
        separado = new javax.swing.JPanel();
        txtCodigoProveedor = new javax.swing.JTextField();
        separador = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        topMenu = new javax.swing.JPanel();
        lbTopMenu = new javax.swing.JLabel();
        jpExit = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 15, 15), 5));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(241, 241, 241));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProveedor.setBackground(new java.awt.Color(241, 241, 241));
        txtProveedor.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtProveedor.setText("Nombre");
        txtProveedor.setBorder(null);
        txtProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtProveedorMousePressed(evt);
            }
        });
        body.add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 71, 190, 21));

        separado.setBackground(new java.awt.Color(16, 15, 15));

        javax.swing.GroupLayout separadoLayout = new javax.swing.GroupLayout(separado);
        separado.setLayout(separadoLayout);
        separadoLayout.setHorizontalGroup(
            separadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        separadoLayout.setVerticalGroup(
            separadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        body.add(separado, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 97, 190, 2));

        txtCodigoProveedor.setBackground(new java.awt.Color(241, 241, 241));
        txtCodigoProveedor.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtCodigoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigoProveedor.setText("Código");
        txtCodigoProveedor.setBorder(null);
        txtCodigoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoProveedorMousePressed(evt);
            }
        });
        body.add(txtCodigoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 25, 190, 21));

        separador.setBackground(new java.awt.Color(16, 15, 15));

        javax.swing.GroupLayout separadorLayout = new javax.swing.GroupLayout(separador);
        separador.setLayout(separadorLayout);
        separadorLayout.setHorizontalGroup(
            separadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        separadorLayout.setVerticalGroup(
            separadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        body.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 51, 190, 2));

        btnEliminar.setBackground(new java.awt.Color(34, 87, 126));
        btnEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(241, 241, 241));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productos/Guardar Producto.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminar.setIconTextGap(15);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        body.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 35));

        jPanel2.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, 284, 182));

        topMenu.setBackground(new java.awt.Color(16, 15, 15));
        topMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTopMenu.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        lbTopMenu.setForeground(new java.awt.Color(241, 241, 241));
        lbTopMenu.setText(".: Proveedores :.");
        topMenu.add(lbTopMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 160, 23));

        jpExit.setBackground(new java.awt.Color(16, 15, 15));
        jpExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpExit.setPreferredSize(new java.awt.Dimension(50, 50));

        lbExit.setBackground(new java.awt.Color(241, 241, 241));
        lbExit.setFont(new java.awt.Font("Roboto Light", 1, 28)); // NOI18N
        lbExit.setForeground(new java.awt.Color(241, 241, 241));
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("X");
        lbExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpExitLayout = new javax.swing.GroupLayout(jpExit);
        jpExit.setLayout(jpExitLayout);
        jpExitLayout.setHorizontalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpExitLayout.setVerticalGroup(
            jpExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        topMenu.add(jpExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 0, -1, 32));

        jPanel2.add(topMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 294, 37));

        header.setBackground(new java.awt.Color(34, 87, 126));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 241, 241));
        jLabel2.setText("Eliminar Proveedor");
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 17, -1, -1));

        jPanel2.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 37, 284, 63));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProveedorMousePressed
        proveedorPresionado();
    }//GEN-LAST:event_txtProveedorMousePressed

    private void txtCodigoProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoProveedorMousePressed
        codigoPresionado();
    }//GEN-LAST:event_txtCodigoProveedorMousePressed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        btnEliminar.setBackground(new Color(0x2b628c));
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(0x2b628c));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(0x22577E));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        btnEliminar.setBackground(new Color(0x2b5574));
    }//GEN-LAST:event_btnEliminarMousePressed

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        cerrarFrameEliminar();
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered
        jpExit.setBackground(new Color(0xF05454));
        lbExit.setForeground(new Color(0x100F0F));
    }//GEN-LAST:event_lbExitMouseEntered

    private void lbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseExited
        jpExit.setBackground(new Color(0x100F0F));
        lbExit.setForeground(new Color(0xF1F1F1));
    }//GEN-LAST:event_lbExitMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProveedoresEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProveedoresEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProveedoresEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProveedoresEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProveedoresEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpExit;
    private javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbTopMenu;
    private javax.swing.JPanel separado;
    private javax.swing.JPanel separador;
    private javax.swing.JPanel topMenu;
    public javax.swing.JTextField txtCodigoProveedor;
    public javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables
}
