/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Conexion;
import static Vista.FrmCompras.txtCodigoProducto;
import static Vista.FrmCompras.txtNombreProducto;
import static Vista.FrmCompras.txtPrecioCompra;
import static Vista.FrmCompras.txtPrecioVenta;
//import static Vista.FrmCompras.jtbVer_Compras;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class FrmSeleccionarProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmSeleccionarProducto
     */
    public FrmSeleccionarProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbSeleccionarProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCampoBuscar = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPopupMenu1.setToolTipText("Enviar Datos");

        jMenuItem1.setText("Enviar Datos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbSeleccionarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtbSeleccionarProducto.setComponentPopupMenu(jPopupMenu1);
        jtbSeleccionarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbSeleccionarProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbSeleccionarProducto);

        jLabel1.setText("Nombre del producto:");

        txtCampoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoBuscarActionPerformed(evt);
            }
        });

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCampoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto)
                    .addComponent(jButton1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoBuscarActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed

        //Variable que sea lo que se le pase al campo
        String campo = txtCampoBuscar.getText();
        //Guardar WHERE
        String consultaWhere = "";

        //Si campo no está vacía...
        if(!"".equals(campo)){
            //Consulta concatenando contenido de txtCampoBuscar
            consultaWhere = "WHERE nombre = '"+ campo +"'";
        }

        try{
            DefaultTableModel modelo = new DefaultTableModel();
            jtbSeleccionarProducto.setModel(modelo);

            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();

            //Consulta JOIN, al final concatenamos consultaWhere par la búsqueda

            //String consulta = "SELECT c.codigo, c.fecha, p.codigo, p.nombre, c.entrada_kg, p.precio_compra, p.precio_venta, c.total_compra, c.observaciones FROM add_products p INNER JOIN compras c ON p.codigo = c.add_products_codigo " + consultaWhere;
            String consulta = "SELECT codigo, nombre, precio_compra, precio_venta FROM add_products " + consultaWhere;

            //String consulta = "SELECT codigo, nombre, entrada_kg FROM "
            ps = con.prepareStatement(consulta);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            //System.out.println(cantidadColumnas);

            modelo.addColumn("Cod Producto");
            modelo.addColumn("Producto");
            modelo.addColumn("Precio Compra");
            modelo.addColumn("Precio Vent");

            while(rs.next()){

                Object[] filas = new Object[cantidadColumnas];

                for(int i=0; i<cantidadColumnas; i++){
                    filas[i] = rs.getObject(i+1);
                }

                modelo.addRow(filas);

            }

        }catch(SQLException e){
            System.err.println(e.toString());
        }

    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        //Enviar datos de la tabla a los campos de texto de otro JFrame
        int filaseleccionada = jtbSeleccionarProducto.getSelectedRow();
        txtCodigoProducto.setText(jtbSeleccionarProducto.getValueAt(filaseleccionada, 0).toString());
        txtNombreProducto.setText(jtbSeleccionarProducto.getValueAt(filaseleccionada, 1).toString());
        txtPrecioCompra.setText(jtbSeleccionarProducto.getValueAt(filaseleccionada, 2).toString());
        txtPrecioVenta.setText(jtbSeleccionarProducto.getValueAt(filaseleccionada, 3).toString());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jtbSeleccionarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbSeleccionarProductoMouseClicked
       
    }//GEN-LAST:event_jtbSeleccionarProductoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSeleccionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSeleccionarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtbSeleccionarProducto;
    private javax.swing.JTextField txtCampoBuscar;
    // End of variables declaration//GEN-END:variables
}
